language: python

python:
    - "3.5"

sudo: false

env:
    - TOXENV="py35-django1.9"
    - TOXENV="py34-django1.9"
    - TOXENV="py27-django1.9"
    - TOXENV="py35-django1.8"
    - TOXENV="py34-django1.8"
    - TOXENV="py33-django1.8"
    - TOXENV="py27-django1.8"
    - TOXENV="py27-django1.10"
    - TOXENV="py35-django1.10"
    - TOXENV="py34-django1.10"

matrix:
    fast_finish: true

install:
    # Virtualenv < 14 is required to keep the Python 3.2 builds running.
    - pip install tox "virtualenv<14"

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV

notifications:
    email: false
